**Anirudhda Pardhi** - s3807109 

## MATH2319 Machine Learning - Solution 2

In [1]:
# Importing required modules
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np 
import math
import seaborn as sns

In [2]:
#importing the csv file
abc = pd.read_csv('THA_diamonds.csv', header=0)
abc.head()

    cut color  depth price  carat
0  Good     D   63.6   low   0.44
1  Fair     F   64.2   low   0.45
2  Good     I   60.4   low   0.50
3  Good     F   56.8   low   0.45
4  Fair     F   64.3   low   0.45

In [3]:
#Copying orignal dataframe to another for reference
df=abc.copy()

## Part A

In [4]:
#Statastical description of data
df['carat'].describe()

count    212.000000
mean       0.667075
std        0.150185
min        0.320000
25%        0.510000
50%        0.700000
75%        0.722500
max        1.010000
Name: carat, dtype: float64

In [5]:
pd.qcut(df['carat'], q=3)

0      (0.319, 0.553]
1      (0.319, 0.553]
2      (0.319, 0.553]
3      (0.319, 0.553]
4      (0.319, 0.553]
            ...
207      (0.71, 1.01]
208      (0.71, 1.01]
209      (0.71, 1.01]
210      (0.71, 1.01]
211      (0.71, 1.01]
Name: carat, Length: 212, dtype: category
Categories (3, interval[float64]): [(0.319, 0.553] < (0.553, 0.71] < (0.71, 1.01]]

In [6]:
df['carat_quantile'] = pd.qcut(df['carat'], q=3)
df.head()

    cut color  depth price  carat  carat_quantile
0  Good     D   63.6   low   0.44  (0.319, 0.553]
1  Fair     F   64.2   low   0.45  (0.319, 0.553]
2  Good     I   60.4   low   0.50  (0.319, 0.553]
3  Good     F   56.8   low   0.45  (0.319, 0.553]
4  Fair     F   64.3   low   0.45  (0.319, 0.553]

In [7]:
df['carat_quantile'].value_counts()

(0.553, 0.71]     79
(0.319, 0.553]    71
(0.71, 1.01]      62
Name: carat_quantile, dtype: int64

In [8]:
bin_labels_3 = ['catagory_1', 'catagory_2', 'catagory_3']
df['carat_label'] = pd.qcut(df['carat'],
                              q=[0, 1/3, 2/3, 1],
                              labels=bin_labels_3)
df.head(10)

    cut color  depth price  carat  carat_quantile carat_label
0  Good     D   63.6   low   0.44  (0.319, 0.553]  catagory_1
1  Fair     F   64.2   low   0.45  (0.319, 0.553]  catagory_1
2  Good     I   60.4   low   0.50  (0.319, 0.553]  catagory_1
3  Good     F   56.8   low   0.45  (0.319, 0.553]  catagory_1
4  Fair     F   64.3   low   0.45  (0.319, 0.553]  catagory_1
5  Fair     F   65.8   low   0.45  (0.319, 0.553]  catagory_1
6  Good     D   63.7   low   0.45  (0.319, 0.553]  catagory_1
7  Good     D   63.7   low   0.45  (0.319, 0.553]  catagory_1
8  Good     D   63.2   low   0.46  (0.319, 0.553]  catagory_1
9  Fair     F   64.9   low   0.50  (0.319, 0.553]  catagory_1

In [9]:
df['depth'].describe()

count    212.000000
mean      62.209906
std        2.832002
min       55.300000
25%       60.100000
50%       63.400000
75%       64.100000
max       68.700000
Name: depth, dtype: float64

In [10]:
pd.qcut(df['depth'], q=3)

0        (61.533, 63.8]
1          (63.8, 68.7]
2      (55.299, 61.533]
3      (55.299, 61.533]
4          (63.8, 68.7]
             ...
207      (61.533, 63.8]
208    (55.299, 61.533]
209        (63.8, 68.7]
210    (55.299, 61.533]
211    (55.299, 61.533]
Name: depth, Length: 212, dtype: category
Categories (3, interval[float64]): [(55.299, 61.533] < (61.533, 63.8] < (63.8, 68.7]]

In [11]:
df['depth_quantile'] = pd.qcut(df['depth'], q=3)
df.head()

,cut,color,depth,price,carat,carat_quantile,carat_label,depth_quantile
0,Good,D,63.6,low,0.44,"(0.319, 0.553]",catagory_1,"(61.533, 63.8]"
1,Fair,F,64.2,low,0.45,"(0.319, 0.553]",catagory_1,"(63.8, 68.7]"
2,Good,I,60.4,low,0.50,"(0.319, 0.553]",catagory_1,"(55.299, 61.533]"
3,Good,F,56.8,low,0.45,"(0.319, 0.553]",catagory_1,"(55.299, 61.533]"
4,Fair,F,64.3,low,0.45,"(0.319, 0.553]",catagory_1,"(63.8, 68.7]"

In [12]:
df['depth_quantile'].value_counts()

(61.533, 63.8]      74
(55.299, 61.533]    71
(63.8, 68.7]        67
Name: depth_quantile, dtype: int64

## Display first 10 rows after discretization

In [13]:
bbin_labels_3 = ['catagory_1', 'catagory_2', 'catagory_3']
df['depth_label'] = pd.qcut(df['depth'],
                              q=[0, 1/3, 2/3, 1],
                              labels=bbin_labels_3)
df.head(10)

,cut,color,depth,price,carat,carat_quantile,carat_label,depth_quantile,depth_label
0,Good,D,63.6,low,0.44,"(0.319, 0.553]",catagory_1,"(61.533, 63.8]",catagory_2
1,Fair,F,64.2,low,0.45,"(0.319, 0.553]",catagory_1,"(63.8, 68.7]",catagory_3
2,Good,I,60.4,low,0.50,"(0.319, 0.553]",catagory_1,"(55.299, 61.533]",catagory_1
3,Good,F,56.8,low,0.45,"(0.319, 0.553]",catagory_1,"(55.299, 61.533]",catagory_1
4,Fair,F,64.3,low,0.45,"(0.319, 0.553]",catagory_1,"(63.8, 68.7]",catagory_3
5,Fair,F,65.8,low,0.45,"(0.319, 0.553]",catagory_1,"(63.8, 68.7]",catagory_3
6,Good,D,63.7,low,0.45,"(0.319, 0.553]",catagory_1,"(61.533, 63.8]",catagory_2
7,Good,D,63.7,low,0.45,"(0.319, 0.553]",catagory_1,"(61.533, 63.8]",catagory_2
8,Good,D,63.2,low,0.46,"(0.319, 0.553]",catagory_1,"(61.533, 63.8]",catagory_2
9,Fair,F,64.9,low,0.50,"(0.319, 0.553]",catagory_1,"(63.8, 68.7]",catagory_3

## Part B 

### Compute the impurity of the price target feature

In [14]:
def compute_impurity(feature, impurity_criterion):
    
    probs = feature.value_counts(normalize=True)
    
    if impurity_criterion == 'entropy':
        impurity = -1 * np.sum(np.log2(probs) * probs)
    elif impurity_criterion == 'gini':
        impurity = 1 - np.sum(np.square(probs))
    else:
        raise ValueError('Unknown impurity criterion')
        
    return(round(impurity, 3))

target_entropy = compute_impurity(df['price'], 'entropy')
target_entropy

1.716

## Part C

In [15]:
df = df.drop(columns=['depth','carat','carat_quantile','depth_quantile'])

In [16]:
df.head()

    cut color price carat_label depth_label
0  Good     D   low  catagory_1  catagory_2
1  Fair     F   low  catagory_1  catagory_3
2  Good     I   low  catagory_1  catagory_1
3  Good     F   low  catagory_1  catagory_1
4  Fair     F   low  catagory_1  catagory_3

In [17]:
def comp_feature_information_gain(df, target, descriptive_feature, split_criterion):
    
    
    print('target feature:', target)
    print('descriptive_feature:', descriptive_feature)
    print('split criterion:', split_criterion)
            
    target_entropy = compute_impurity(df[target], split_criterion)

    # we define two lists below:
    # entropy_list to store the entropy of each partition
    # weight_list to store the relative number of observations in each partition
    entropy_list = list()
    weight_list = list()
    
    # loop over each level of the descriptive feature
    # to partition the dataset with respect to that level
    # and compute the entropy and the weight of the level's partition
    for level in df[descriptive_feature].unique():
        df_feature_level = df[df[descriptive_feature] == level]
        entropy_level = compute_impurity(df_feature_level[target], split_criterion)
        entropy_list.append(round(entropy_level, 3))
        weight_level = len(df_feature_level) / len(df)
        weight_list.append(round(weight_level, 3))

    print('impurity of partitions:', entropy_list)
    print('weights of partitions:', weight_list)

    feature_remaining_impurity = np.sum(np.array(entropy_list) * np.array(weight_list))
    print('remaining impurity:', feature_remaining_impurity)
    
    information_gain = target_entropy - feature_remaining_impurity
    print('information gain:', information_gain)
    
    print('====================')

    return(information_gain)

In [18]:
##entropy split criteria
split_criterion = 'entropy'
for feature in df.drop(columns='price').columns:
    feature_info_gain = comp_feature_information_gain(df, 'price', feature, split_criterion)

target feature: price
descriptive_feature: cut
split criterion: entropy
impurity of partitions: [1.68, 1.78]
weights of partitions: [0.717, 0.283]
remaining impurity: 1.7083
information gain: 0.00770000000000004
====================
target feature: price
descriptive_feature: color
split criterion: entropy
impurity of partitions: [1.657, 1.445, 1.833]
weights of partitions: [0.269, 0.434, 0.297]
remaining impurity: 1.617264
information gain: 0.09873599999999993
====================
target feature: price
descriptive_feature: carat_label
split criterion: entropy
impurity of partitions: [-0.0, 1.365, 1.529]
weights of partitions: [0.335, 0.373, 0.292]
remaining impurity: 0.9556129999999998
information gain: 0.7603870000000001
====================
target feature: price
descriptive_feature: depth_label
split criterion: entropy
impurity of partitions: [1.517, 1.749, 1.74]
weights of partitions: [0.349, 0.316, 0.335]
remaining impurity: 1.6650170000000002
information gain: 0.05098299999999978
====================

In [31]:
split_table = {'split': ['cut', 'color', 'carat','depth'],
        'remainder': [1.708, 1.617, 0.955,1.665],
        'info_gain': [0.007, 0.098, 0.76,0.050],
        'is_optimal': ['False', 'False', 'True','False']}
df_splits = pd.DataFrame(split_table)

### df_splits table

In [32]:
df_splits

   split  remainder  info_gain is_optimal
0    cut      1.708      0.007      False
1  color      1.617      0.098      False
2  carat      0.955      0.760       True
3  depth      1.665      0.050      False

## Part D

In [20]:
# selecting required columns of carat catagory and price
x_data = df[['carat_label','price']]

In [21]:
x_data.head()

  carat_label price
0  catagory_1   low
1  catagory_1   low
2  catagory_1   low
3  catagory_1   low
4  catagory_1   low

In [22]:
# subsetting dataframes according to catagories
df_cat1 = x_data[(x_data['carat_label'] == 'catagory_1')]
df_cat2 = x_data[(x_data['carat_label'] == 'catagory_2')]
df_cat3 = x_data[(x_data['carat_label'] == 'catagory_3')]

In [23]:
# checking catagory wise prbability on complete dataset
for level in x_data['carat_label'].unique():
    print('level name:', level)
    df_feature_level = x_data[x_data['carat_label'] == level]
    print('corresponding data partition:')
    print(df_feature_level)
    print('partition target feature impurity:', compute_impurity(df_feature_level['price'], 'entropy'))
    print('partition weight:', str(len(df_feature_level)) + '/' + str(len(x_data)))
    print('====================')

level name: catagory_1
corresponding data partition:
   carat_label price
0   catagory_1   low
1   catagory_1   low
2   catagory_1   low
3   catagory_1   low
4   catagory_1   low
..         ...   ...
79  catagory_1   low
80  catagory_1   low
81  catagory_1   low
83  catagory_1   low
86  catagory_1   low

[71 rows x 2 columns]
partition target feature impurity: -0.0
partition weight: 71/212
====================
level name: catagory_2
corresponding data partition:
    carat_label    price
11   catagory_2      low
15   catagory_2      low
16   catagory_2      low
27   catagory_2      low
34   catagory_2      low
..          ...      ...
172  catagory_2     high
173  catagory_2     high
174  catagory_2     high
175  catagory_2     high
198  catagory_2  premium

[79 rows x 2 columns]
partition target feature impurity: 1.365
partition weight: 79/212
====================
level name: catagory_3
corresponding data partition:
    carat_label    price
99   catagory_3   medium
103  catagory_3   medium
105  catagory_3   medium
119  catagory_3   medium
124  catagory_3   medium
..          ...      ...
207  catagory_3  premium
208  catagory_3  premium
209  catagory_3  premium
210  catagory_3  premium
211  catagory_3  premium

[62 rows x 2 columns]
partition target feature impurity: 1.529
partition weight: 62/212
====================

In [24]:
# checking probablity of prices on catagory 1
for level in df_cat1['price'].unique():
    print('level name:', level)
    df_feature_level = df_cat1[df_cat1['price'] == level]
    print('corresponding data partition:')
    print(df_feature_level)
    print('partition target feature impurity:', compute_impurity(df_feature_level['carat_label'], 'entropy'))
    print('partition weight:', str(len(df_feature_level)) + '/' + str(len(df_cat1)))
    print('====================')

level name: low
corresponding data partition:
   carat_label price
0   catagory_1   low
1   catagory_1   low
2   catagory_1   low
3   catagory_1   low
4   catagory_1   low
..         ...   ...
79  catagory_1   low
80  catagory_1   low
81  catagory_1   low
83  catagory_1   low
86  catagory_1   low

[71 rows x 2 columns]
partition target feature impurity: -0.0
partition weight: 71/71
====================

C:\Users\ADMIN\anaconda3\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [25]:
# saving the above results in variables for future references
cat1_low = 71/71
cat1_med = 0
cat1_high = 0
cat1_prem = 0

In [26]:
# checking probablity of prices on catagory 2
for level in df_cat2['price'].unique():
    print('level name:', level)
    df_feature_level = df_cat2[df_cat2['price'] == level]
    print('corresponding data partition:')
    print(df_feature_level)
    print('partition target feature impurity:', compute_impurity(df_feature_level['carat_label'], 'entropy'))
    print('partition weight:', str(len(df_feature_level)) + '/' + str(len(df_cat2)))
    print('====================')

level name: low
corresponding data partition:
   carat_label price
11  catagory_2   low
15  catagory_2   low
16  catagory_2   low
27  catagory_2   low
34  catagory_2   low
42  catagory_2   low
43  catagory_2   low
52  catagory_2   low
65  catagory_2   low
66  catagory_2   low
68  catagory_2   low
74  catagory_2   low
77  catagory_2   low
82  catagory_2   low
84  catagory_2   low
85  catagory_2   low
87  catagory_2   low
88  catagory_2   low
89  catagory_2   low
90  catagory_2   low
91  catagory_2   low
92  catagory_2   low
partition target feature impurity: -0.0
partition weight: 22/79
====================
level name: medium
corresponding data partition:
    carat_label   price
93   catagory_2  medium
94   catagory_2  medium
95   catagory_2  medium
96   catagory_2  medium
97   catagory_2  medium
98   catagory_2  medium
100  catagory_2  medium
101  catagory_2  medium
102  catagory_2  medium
104  catagory_2  medium
106  catagory_2  medium
107  catagory_2  medium
108  catagory_2  medium
109  catagory_2  medium
110  catagory_2  medium
111  catagory_2  medium
112  catagory_2  medium
113  catagory_2  medium
114  catagory_2  medium
115  catagory_2  medium
116  catagory_2  medium
117  catagory_2  medium
118  catagory_2  medium
120  catagory_2  medium
121  catagory_2  medium
122  catagory_2  medium
123  catagory_2  medium
126  catagory_2  medium
127  catagory_2  medium
129  catagory_2  medium
130  catagory_2  medium
132  catagory_2  medium
135  catagory_2  medium
136  catagory_2  medium
137  catagory_2  medium
138  catagory_2  medium
148  catagory_2  medium
149  catagory_2  medium
150  catagory_2  medium
152  catagory_2  medium
153  catagory_2  medium
154  catagory_2  medium
155  catagory_2  medium
156  catagory_2  medium
160  catagory_2  medium
161  catagory_2  medium
163  catagory_2  medium
166  catagory_2  medium
partition target feature impurity: -0.0
partition weight: 48/79
====================
level name: high
corresponding data partition:
    carat_label price
167  catagory_2  high
168  catagory_2  high
170  catagory_2  high
171  catagory_2  high
172  catagory_2  high
173  catagory_2  high
174  catagory_2  high
175  catagory_2  high
partition target feature impurity: -0.0
partition weight: 8/79
====================
level name: premium
corresponding data partition:
    carat_label    price
198  catagory_2  premium
partition target feature impurity: -0.0
partition weight: 1/79
====================

C:\Users\ADMIN\anaconda3\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\ADMIN\anaconda3\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\ADMIN\anaconda3\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\ADMIN\anaconda3\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [27]:
# saving the above results in variables for future references
cat2_low = 22/79
cat2_med = 48/79
cat2_high = 8/79
cat2_prem = 1/79

In [28]:
# checking probablity of prices on catagory 3
for level in df_cat3['price'].unique():
    print('level name:', level)
    df_feature_level = df_cat3[df_cat3['price'] == level]
    print('corresponding data partition:')
    print(df_feature_level)
    print('partition target feature impurity:', compute_impurity(df_feature_level['carat_label'], 'entropy'))
    print('partition weight:', str(len(df_feature_level)) + '/' + str(len(df_cat3)))
    print('====================')

level name: medium
corresponding data partition:
    carat_label   price
99   catagory_3  medium
103  catagory_3  medium
105  catagory_3  medium
119  catagory_3  medium
124  catagory_3  medium
125  catagory_3  medium
128  catagory_3  medium
131  catagory_3  medium
133  catagory_3  medium
134  catagory_3  medium
139  catagory_3  medium
140  catagory_3  medium
141  catagory_3  medium
142  catagory_3  medium
143  catagory_3  medium
144  catagory_3  medium
145  catagory_3  medium
146  catagory_3  medium
147  catagory_3  medium
151  catagory_3  medium
157  catagory_3  medium
158  catagory_3  medium
159  catagory_3  medium
162  catagory_3  medium
164  catagory_3  medium
165  catagory_3  medium
partition target feature impurity: -0.0
partition weight: 26/62
====================
level name: high
corresponding data partition:
    carat_label price
169  catagory_3  high
176  catagory_3  high
177  catagory_3  high
178  catagory_3  high
179  catagory_3  high
180  catagory_3  high
181  catagory_3  high
182  catagory_3  high
183  catagory_3  high
184  catagory_3  high
185  catagory_3  high
186  catagory_3  high
187  catagory_3  high
188  catagory_3  high
189  catagory_3  high
190  catagory_3  high
191  catagory_3  high
192  catagory_3  high
193  catagory_3  high
194  catagory_3  high
195  catagory_3  high
196  catagory_3  high
197  catagory_3  high
partition target feature impurity: -0.0
partition weight: 23/62
====================
level name: premium
corresponding data partition:
    carat_label    price
199  catagory_3  premium
200  catagory_3  premium
201  catagory_3  premium
202  catagory_3  premium
203  catagory_3  premium
204  catagory_3  premium
205  catagory_3  premium
206  catagory_3  premium
207  catagory_3  premium
208  catagory_3  premium
209  catagory_3  premium
210  catagory_3  premium
211  catagory_3  premium
partition target feature impurity: -0.0
partition weight: 13/62
====================

C:\Users\ADMIN\anaconda3\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\ADMIN\anaconda3\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\ADMIN\anaconda3\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [29]:
# saving the above results in variables for future references
cat3_low = 0
cat3_med = 26/62
cat3_high = 23/62
cat3_prem = 13/62

In [35]:
#creating predict table
predict_table = {'leaf_condition': ['catagory1', 'catagory2', 'catagory3'],
                'low_price_prob': [cat1_low , cat2_low  , cat3_low],
                'medium_price_prob': [cat1_med , cat2_med  , cat3_med],
                'high_price_prob': [cat1_high , cat2_high  , cat3_high],
                'premium_price_prob': [cat1_prem , cat2_prem  , cat3_prem],
                'leaf_prediction': ['low' , 'medium'  , 'medium']}
df_pred = pd.DataFrame(predict_table)

### df_pred table

In [36]:
df_pred

,leaf_condition,low_price_prob,medium_price_prob,high_price_prob,premium_price_prob,leaf_prediction
0,catagory1,1.000000,0.000000,0.000000,0.000000,low
1,catagory2,0.278481,0.607595,0.101266,0.012658,medium
2,catagory3,0.000000,0.419355,0.370968,0.209677,medium